name: Java CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessário para o commit dos badges

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      
      - run: chmod +x gradlew
      - run: ./gradlew build
      
      - name: Generate coverage badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: badges  # Pasta específica para organização
          generate-branches-badge: true  # Gera badge adicional
      
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update coverage badges'
          add: 'badges/*.svg'  # Apenas os badges na pasta específica
          # Comportamento inteligente: só commita se houver alteração
      
      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: testReport
          path: build/reports/tests/test
          retention-days: 1  # Mantém por 1 dia conforme solicitado